# Generated by Django 6.0.3 on 2026-03-18 15:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bloque',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.PositiveIntegerField(unique=True)),
                ('hora_inicio', models.TimeField()),
                ('hora_termino', models.TimeField()),
                ('jornada', models.CharField(choices=[('DIURNA', 'Diurna'), ('VESPERTINA', 'Vespertina')], max_length=20)),
                ('activo', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Bloque',
                'verbose_name_plural': 'Bloques',
                'ordering': ['numero'],
            },
        ),
        migrations.CreateModel(
            name='CargaArchivo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('archivo', models.FileField(upload_to='cargas_excel/')),
                ('nombre_original', models.CharField(max_length=255)),
                ('fecha_carga', models.DateTimeField(auto_now_add=True)),
                ('total_registros', models.PositiveIntegerField(default=0)),
                ('observacion', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Carga de archivo',
                'verbose_name_plural': 'Cargas de archivos',
                'ordering': ['-fecha_carga'],
            },
        ),
        migrations.CreateModel(
            name='Docente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rut', models.CharField(max_length=20, unique=True)),
                ('nombre', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': 'Docente',
                'verbose_name_plural': 'Docentes',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='RegistroClase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_clase', models.DateField()),
                ('jornada_texto', models.CharField(blank=True, max_length=100, null=True)),
                ('sede', models.CharField(blank=True, max_length=150, null=True)),
                ('sala', models.CharField(blank=True, max_length=150, null=True)),
                ('programa_estudio', models.CharField(blank=True, max_length=255, null=True)),
                ('codigo_asignatura', models.CharField(blank=True, max_length=100, null=True)),
                ('asignatura', models.CharField(blank=True, max_length=255, null=True)),
                ('seccion', models.CharField(blank=True, max_length=100, null=True)),
                ('sub_seccion', models.CharField(blank=True, max_length=100, null=True)),
                ('modalidad', models.CharField(blank=True, max_length=100, null=True)),
                ('dia', models.CharField(blank=True, max_length=50, null=True)),
                ('modulo_inicio', models.PositiveIntegerField()),
                ('modulo_termino', models.PositiveIntegerField(blank=True, null=True)),
                ('asistentes', models.PositiveIntegerField(default=0)),
                ('alumnos_totales', models.PositiveIntegerField(default=0)),
                ('materias_revisadas', models.TextField(blank=True, null=True)),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('fecha_retiro', models.DateTimeField(blank=True, null=True)),
                ('fecha_devolucion', models.DateTimeField(blank=True, null=True)),
                ('carga', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registros', to='atrasos.cargaarchivo')),
                ('docente', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='registros_clase', to='atrasos.docente')),
            ],
            options={
                'verbose_name': 'Registro de clase',
                'verbose_name_plural': 'Registros de clases',
                'ordering': ['-fecha_clase', 'modulo_inicio', 'docente__nombre'],
            },
        ),
        migrations.CreateModel(
            name='AtrasoDocente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_hora_programada', models.DateTimeField(blank=True, null=True)),
                ('minutos_atraso', models.IntegerField(blank=True, null=True)),
                ('estado', models.CharField(choices=[('A_TIEMPO', 'A tiempo'), ('TOLERANCIA', 'Tolerancia'), ('LEVE', 'Atraso leve'), ('MEDIO', 'Atraso medio'), ('GRAVE', 'Atraso grave'), ('SIN_RETIRO', 'Sin retiro'), ('SIN_BLOQUE', 'Bloque no configurado'), ('INCONSISTENTE', 'Dato inconsistente')], default='SIN_BLOQUE', max_length=20)),
                ('observacion_calculo', models.CharField(blank=True, max_length=255, null=True)),
                ('bloque', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='atrasos', to='atrasos.bloque')),
                ('registro_clase', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='atraso', to='atrasos.registroclase')),
            ],
            options={
                'verbose_name': 'Atraso docente',
                'verbose_name_plural': 'Atrasos docentes',
                'ordering': ['-fecha_hora_programada'],
            },
        ),
    ]
