"""
Django settings for control_atrasos_docentes project.

Generated by 'django-admin startproject' using Django 6.0.3.
"""

import os
from pathlib import Path

BASE_DIR = Path(__file__).resolve().parent.parent


# =========================================================
# SEGURIDAD / ENTORNO
# =========================================================

# En producción usar siempre variable de entorno.
# Si no existe, deja una clave local solo para desarrollo.
SECRET_KEY = os.getenv(
    "SECRET_KEY",
    "clave-local-solo-desarrollo-cambiar-antes-de-produccion"
)

# DEBUG controlado por variable de entorno.
DEBUG = os.getenv("DEBUG", "True").strip().lower() == "true"

# Hosts permitidos por variable de entorno
ALLOWED_HOSTS_ENV = os.getenv("ALLOWED_HOSTS", "")
ALLOWED_HOSTS = [
    host.strip()
    for host in ALLOWED_HOSTS_ENV.split(",")
    if host.strip()
]

# Orígenes confiables para CSRF por variable de entorno
CSRF_TRUSTED_ORIGINS_ENV = os.getenv("CSRF_TRUSTED_ORIGINS", "")
CSRF_TRUSTED_ORIGINS = [
    origin.strip()
    for origin in CSRF_TRUSTED_ORIGINS_ENV.split(",")
    if origin.strip()
]

# Valores mínimos para local + Azure
HOSTS_BASE = [
    "127.0.0.1",
    "localhost",
    ".azurewebsites.net",
]

for host in HOSTS_BASE:
    if host not in ALLOWED_HOSTS:
        ALLOWED_HOSTS.append(host)

# Opcional: permitir host interno detectado por Azure
WEBSITE_HOSTNAME = os.getenv("WEBSITE_HOSTNAME", "").strip()
if WEBSITE_HOSTNAME and WEBSITE_HOSTNAME not in ALLOWED_HOSTS:
    ALLOWED_HOSTS.append(WEBSITE_HOSTNAME)

# Si viene URL principal desde entorno, agregarla automáticamente a CSRF
APP_URL = os.getenv("APP_URL", "").strip()
if APP_URL and APP_URL not in CSRF_TRUSTED_ORIGINS:
    CSRF_TRUSTED_ORIGINS.append(APP_URL)


# =========================================================
# APLICACIONES
# =========================================================

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'atrasos',
]


# =========================================================
# MIDDLEWARE
# =========================================================

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]


# =========================================================
# URLS / TEMPLATES / WSGI
# =========================================================

ROOT_URLCONF = 'control_atrasos_docentes.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'control_atrasos_docentes.wsgi.application'


# =========================================================
# BASE DE DATOS
# =========================================================

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# =========================================================
# VALIDADORES DE CONTRASEÑA
# =========================================================

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# =========================================================
# INTERNACIONALIZACIÓN
# =========================================================

LANGUAGE_CODE = 'es-cl'
TIME_ZONE = 'America/Santiago'
USE_I18N = True
USE_TZ = True


# =========================================================
# ARCHIVOS ESTÁTICOS Y MEDIA
# =========================================================

STATIC_URL = '/static/'
STATIC_ROOT = BASE_DIR / 'staticfiles'
STATICFILES_STORAGE = 'whitenoise.storage.CompressedManifestStaticFilesStorage'

MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'


# =========================================================
# SUBIDA DE ARCHIVOS
# =========================================================

DATA_UPLOAD_MAX_MEMORY_SIZE = 25 * 1024 * 1024
FILE_UPLOAD_MAX_MEMORY_SIZE = 25 * 1024 * 1024


# =========================================================
# CONFIGURACIÓN DE SEGURIDAD PARA PRODUCCIÓN
# =========================================================

if not DEBUG:
    SESSION_COOKIE_SECURE = True
    CSRF_COOKIE_SECURE = True
    SECURE_CONTENT_TYPE_NOSNIFF = True
    X_FRAME_OPTIONS = 'DENY'
    SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')